import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/provider/ThemeProvider";
import { ClerkProvider } from "@clerk/nextjs";
import { enUS } from "@clerk/localizations";
import { Toaster } from "sonner";
import StreamProvider from "@/provider/StreamProvider";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const clerkLocalization = {
    ...enUS,
    signIn: {
      ...enUS.signIn,
      start: {
        ...enUS.signIn?.start,
        title: "Welcome To Selllio",
      },
    },
  };

  return (
    <ClerkProvider
      localization={clerkLocalization}
      appearance={{
        layout: {
          logoPlacement: "inside",
        },
        elements: {
          rootBox: "mx-auto",
          card: "bg-[#0a0a0a] border border-white/10",
          headerTitle: "text-white",
          headerSubtitle: "text-white/60",
          socialButtonsBlockButton: "border-white/10 text-white hover:bg-white/5",
          formButtonPrimary: "bg-gradient-to-r from-indigo-500 to-rose-500 hover:opacity-90",
          footerActionLink: "text-indigo-400 hover:text-indigo-300",
          formFieldInput: "bg-white/5 border-white/10 text-white",
          formFieldLabel: "text-white/80",
          identityPreviewText: "text-white",
          identityPreviewEditButton: "text-indigo-400",
        },
        variables: {
          colorPrimary: "#6366f1",
          colorText: "#ffffff",
          colorBackground: "#0a0a0a",
        },
      }}
    >
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${manrope.variable} antialiased font-manrope`}
          suppressHydrationWarning
        >
          <StreamProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="dark"
              enableSystem
              disableTransitionOnChange
            >
              {children}
              <Toaster richColors />
            </ThemeProvider>
          </StreamProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
